# To start the container run docker-compose up (-d switch for silent mode) in a terminal console.

services:
    mssql:
        container_name: marketplace-db
        hostname: marketplace-db
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: 'Y'
            MSSQL_SA_PASSWORD: 'P@ssw0rd!'   # change this to your secure password
            MSSQL_PID: 'developer'
        ports:
            - "1433:1433"
             
