# To start the container run docker-compose up (-d switch for silent mode) in a terminal console.

services:
  mssql:
    container_name: marketplace-db
    hostname: marketplace-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'P@ssw0rd!'
      MSSQL_PID: 'developer'
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd!' -C -Q 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  mailhog:
    container_name: marketplace-mailhog
    hostname: marketplace-mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web UI port
    environment:
      MH_STORAGE: memory
    restart: unless-stopped

  garage:
    image: dxflrs/garage:v1.0.1
    container_name: garage
    ports:
      - "3900:3900"  # S3 API
      - "3901:3901"  # RPC
      - "3902:3902"  # S3 Web
      - "3903:3903"  # Admin API
      - "3904:3904"  # K2V API (optional)
    environment:
      - RUST_LOG=garage=info
    command: ["/garage", "-c", "/tmp/garage.toml", "server"]
    volumes:
      - ./garage.toml:/tmp/garage.toml:ro
      - garage_data:/var/lib/garage
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  garage_data:
