# To start the container run docker-compose up (-d switch for silent mode) in a terminal console.

services:
  mssql:
    container_name: marketplace-db
    hostname: marketplace-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'P@ssw0rd!'
      MSSQL_PID: 'developer'
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd!' -C -Q 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  
  mailhog:
    container_name: marketplace-mailhog
    hostname: marketplace-mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web UI port
    environment:
      MH_STORAGE: memory
    restart: unless-stopped