metadata_dir = "/data/meta"
data_dir = "/data/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "f3ebb90c60c7cba6f27b657dd3273cedbc9647b4b86b10376c300850c2b16f7d"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "qAYRnZvWThesImOCTUmTWfKvCVRqk9mgakoHHBzyq+Y="
metrics_token = "lJrSXr1bpf8HIiDKBc4ucS2TqGBPzB+Qwmw7quVg5rw="
